name: terraform_validate

on: [push]

jobs:
  terraform-validate:
    
    runs-on: ubuntu-latest

    container:
      image: docker://hashicorp/terraform:latest

    steps:
    - uses: actions/checkout@v1

    - name: Init Terraform
      run: terraform init

    # - name: Validate Terraform plan
    #   run: terraform validate
